### ISSUE TITLE
can we get a more fud one ?

### ISSUE THREAD

**Issue by minanagehsalalma** [XXH3X/USBStealer#2]

**Comment by XXH3X** [comment]
Sorry, no longer working on the project :/
Either way I'm do not  want to be responsible for any harm caused by these programs. I've wrote the scripts just for fun, which I no longer see interest in :s

**Comment by minanagehsalalma** [comment]
> Sorry, no longer working on the project :/
> Either way I'm do not want to be responsible for any harm caused by these programs. I've wrote the scripts just for fun, which I no longer see interest in :s

No problem mate...  keep going on.
